// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyqrhuluxubcayrmujkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cXJodWx1eHViY2F5cm11amt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTQ3MTIsImV4cCI6MjA2NDc5MDcxMn0.YtPrdcowWYo3h_ZtispFTvzVD-ilL0ERY3SClZQ52Qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);